#spring:
#  datasource:
#      url: jdbc:postgresql://localhost:5440/AutoBase2
#      username: sa
#      password: admin
#      driverClassName: org.postgresql.Driver
#
#  flyway:
#      enabled: true
#      user: sa
#      password: admin
#      schemas: public
#      url: jdbc:postgresql://localhost:5440/AutoBase2

spring:
    datasource:
        url: jdbc:postgresql://postgre-serv.postgres.database.azure.com:5432/newData
        username: adminElena
        password: Oleg+Lena=22
        driverClassName: org.postgresql.Driver

    flyway:
        enabled: true
        user: adminElena
        password: Oleg+Lena=22
        schemas: public
        url: jdbc:postgresql://postgre-serv.postgres.database.azure.com:5432/newData



